/origami/stlFile geometry/miura_deployed_silicon.stl
/origami/kaptonStlFile geometry/miura_deployed_kapton.stl
/origami/sensorThickness 0.300 mm
/origami/substrateThickness 0.050 mm
/origami/foldState 1.0
/origami/gun/mode mark1cone
/origami/gun/fixedAngleDeg 0
/origami/gun/momentumGeV 5.0
/origami/gun/gunZmm 300
/origami/gun/diskRadiusMm 150
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/initialize
/run/beamOn 1000
