/origami/stlFile geometry/miura_deployed_silicon.gdml
/origami/kaptonStlFile geometry/miura_deployed_kapton.gdml
/origami/sensorThickness 0.300 mm
/origami/substrateThickness 0.050 mm
/origami/foldState 1.0
/origami/gun/mode isotropic4pi
/origami/gun/momentumGeV 5.0
/origami/gun/vertexSmearMm 3.0
/run/initialize
/vis/open OGL 800x800-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/scene/endOfEventAction accumulate 30
/vis/viewer/set/autoRefresh true
/vis/viewer/refresh
/run/beamOn 20
