/origami/stlFile geometry/yoshimura_deployed_silicon.stl
/origami/kaptonStlFile geometry/yoshimura_deployed_kapton.stl
/origami/sensorThickness 0.300 mm
/origami/substrateThickness 0.050 mm
/origami/foldState 1.0
/origami/gun/fixedAngleDeg 0
/origami/gun/momentumGeV 5.0
/origami/gun/gunZmm 300
/origami/gun/diskRadiusMm 80
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/initialize
/run/beamOn 10000
